Algoritmo "Trabalhando com Tipos"

Var
palavra1, palavra2, palavra3: caracter
numero1, numero2, numero3: inteiro

Inicio
Escreval("Palavra 1:")
Leia(palavra1)
Escreval("Palavra 2:")
Leia(palavra2)
Escreval("Número 1:")
Leia(numero1)
Escreval("Número 2:")
Leia(numero2)
palavra3 <- palavra1 + palavra2
numero3 <- numero1 + numero2
Escreval(palavra3)
Escreval(numero3)


Fimalgoritmo