Algoritmo "Trabalhando com Tipos"

Var
numero1, numero2, soma, subtracao, multiplicacao: inteiro
divisao: real
sucesso: logico
Inicio
      Escreval("N1")
      Leia(numero1)
      Escreval("N2")
      Leia(numero2)
      //soma <- numero1 + numero2
      //subtracao <- numero1 - numero2
      //multiplicacao <- numero1 * numero2
      //divisao <- numero1 / numero2
      sucesso <- numero1 > 10
      escreval(sucesso)
      


Fimalgoritmo